CREATE TABLE ENDERECO (
    CODENDERECO INT,
    NOME VARCHAR(255),
    RUA VARCHAR(255),
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255),
    CEP VARCHAR(20),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(100),        
    PAIS VARCHAR(100),
    PRIMARY KEY(CODENDERECO)
);

CREATE TABLE EMPRESA (
    CODEMPRESA INT PRIMARY KEY,
    NOMEFANTASIA VARCHAR(255),
    NOME VARCHAR(255),
    CNPJ VARCHAR(20),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(255),
    IMAGEM LONGBLOB,
    CODENDERECO INT,
    FOREIGN KEY (CODENDERECO) REFERENCES ENDERECO(CODENDERECO)
);

CREATE TABLE USUARIO (
    CODUSUARIO INT,
    NOME VARCHAR(255),
    USUARIO VARCHAR(255),
    SENHA VARCHAR(255),
    ATIVO INT,
    ULTIMOLOGIN DATETIME,
    PRIMARY KEY (CODUSUARIO)
);

CREATE TABLE PERFIL (
		CODEMPRESA INT,
    CODPERFIL INT,
    NOME VARCHAR(255),
    ATIVO INT,
    PRIMARY KEY (CODEMPRESA, CODPERFIL)
);

CREATE TABLE USUARIOPERFIL (
    CODEMPRESA INT,
    CODUSUARIO INT,
    CODPERFIL INT,
    PRIMARY KEY (CODEMPRESA, CODUSUARIO, CODPERFIL),
    FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO(CODUSUARIO),
    FOREIGN KEY (CODEMPRESA, CODPERFIL) REFERENCES PERFIL(CODEMPRESA, CODPERFIL)
);

CREATE TABLE CLIENTEFORNECEDOR (
    CODEMPRESA INT,
    CODCLIFOR INT,
    NOME VARCHAR(255),
    NOMEFANTASIA VARCHAR(255),
    CNPJCPF VARCHAR(20),
    TELEFONE VARCHAR(20),
    TIPOCADASTRO INT,
    TIPOPESSOA INT,
    EMAIL VARCHAR(255),
    CODENDERECO INT, 
    PRIMARY KEY (CODEMPRESA, CODCLIFOR),
    FOREIGN KEY (CODEMPRESA) REFERENCES EMPRESA(CODEMPRESA),
    FOREIGN KEY (CODENDERECO) REFERENCES ENDERECO(CODENDERECO)
);

CREATE TABLE CLASSIFICACAO (
    CODEMPRESA INT,
    CODCLASSIFICACAO INT,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255),
    PRIMARY KEY (CODEMPRESA, CODCLASSIFICACAO),
    FOREIGN KEY (CODEMPRESA) REFERENCES EMPRESA(CODEMPRESA)
);

CREATE TABLE PRODUTO (
    CODEMPRESA INT,
    CODPRODUTO INT,
    TIPO INT,
    ATIVO INT,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255),
    PRECOUNITARIO DECIMAL(10,2),
    CUSTO DECIMAL(10,2),
    MARGEM DECIMAL(10,2),
    CODCLASSIFICACAO INT,
    PRIMARY KEY (CODEMPRESA, CODPRODUTO),
    FOREIGN KEY (CODEMPRESA, CODCLASSIFICACAO) REFERENCES CLASSIFICACAO(CODEMPRESA, CODCLASSIFICACAO)
);

CREATE TABLE PRODUTOCLIFOR (
    CODEMPRESA INT,
    CODPRODUTO INT,
    CODCLIFOR INT,
    ATIVO INT,
    VALOR DECIMAL(10,2),
    PRIMARY KEY (CODEMPRESA, CODPRODUTO, CODCLIFOR),
    FOREIGN KEY (CODEMPRESA, CODPRODUTO) REFERENCES PRODUTO(CODEMPRESA, CODPRODUTO),
    FOREIGN KEY (CODEMPRESA, CODCLIFOR) REFERENCES CLIENTEFORNECEDOR(CODEMPRESA, CODCLIFOR)
);

CREATE TABLE CONTROLEESTOQUE (
    CODEMPRESA INT,
    CODPRODUTO INT,
    QUANTIDADEATUAL DECIMAL(10,2),
    QUANTIDADESALDO DECIMAL(10,2),
    QUANTIDADERESERVADA DECIMAL(10,2),
    DATA DATE,
    PRIMARY KEY (CODEMPRESA, CODPRODUTO),
    FOREIGN KEY (CODEMPRESA, CODPRODUTO) REFERENCES PRODUTO(CODEMPRESA, CODPRODUTO)
);

CREATE TABLE MOVIMENTACAO (
    CODEMPRESA INT,
    CODMOVIMENTACAO INT,
    STATUS INT,
    VALORTOTAL DECIMAL(10,2),
    CODUSUARIO INT,
    CODCLIFOR INT,
    TIPOMOVIMENTO VARCHAR(50),
    DATA DATE,
    OBSERVACAO VARCHAR(255),
    PRIMARY KEY (CODEMPRESA, CODMOVIMENTACAO),
    FOREIGN KEY (CODEMPRESA) REFERENCES EMPRESA(CODEMPRESA),
    FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO(CODUSUARIO),
    FOREIGN KEY (CODEMPRESA, CODCLIFOR) REFERENCES CLIENTEFORNECEDOR(CODEMPRESA, CODCLIFOR)
);

CREATE TABLE MOVIMENTACAOITEM (
    CODEMPRESA INT,
    CODMOVIMENTACAO INT,
    CODMOVIMENTACAOITEM INT,
    CODPRODUTO INT,
    QUANTIDADE DECIMAL(10,2),
    VALORUNITARIO DECIMAL(10,2),
    CUSTOUNITARIO DECIMAL(10,2),
    VALORTOTAL DECIMAL(10,2),
    PRIMARY KEY (CODEMPRESA, CODMOVIMENTACAO, CODMOVIMENTACAOITEM),
    FOREIGN KEY (CODEMPRESA, CODMOVIMENTACAO) REFERENCES MOVIMENTACAO(CODEMPRESA, CODMOVIMENTACAO),
    FOREIGN KEY (CODEMPRESA, CODPRODUTO) REFERENCES PRODUTO(CODEMPRESA, CODPRODUTO)
);

CREATE TABLE DICIONARIO 
(
		TABELA VARCHAR(120),
    COLUNA VARCHAR(120),
    DESCRICAO VARCHAR(120),
    
    PRIMARY KEY(TABELA, COLUNA)
);

-- DICIONARIO USUARIO
INSERT INTO DICIONARIO VALUES ('USUARIO', 'CODUSUARIO', 'Cód. Usuário');
INSERT INTO DICIONARIO VALUES ('USUARIO', 'USUARIO', 'Usuário');
INSERT INTO DICIONARIO VALUES ('USUARIO', 'Ativo', 'Ativo');
INSERT INTO DICIONARIO VALUES ('USUARIO', 'NOME', 'Nome');
INSERT INTO DICIONARIO VALUES ('USUARIO', 'SENHA', 'Senha');
INSERT INTO DICIONARIO VALUES ('USUARIO', 'ULTIMOLOGIN', 'Último Login');

-- DICIONARIO EMPRESA
INSERT INTO DICIONARIO VALUES ('EMPRESA', 'CODEMPRESA', 'Cód. Empresa');
INSERT INTO DICIONARIO VALUES ('EMPRESA', 'NOMEFANTASIA', 'Nome Fantasia');
INSERT INTO DICIONARIO VALUES ('EMPRESA', 'NOME', 'Nome');
INSERT INTO DICIONARIO VALUES ('EMPRESA', 'TELEFONE', 'Telefone');
INSERT INTO DICIONARIO VALUES ('EMPRESA', 'EMAIL', 'Email');
INSERT INTO DICIONARIO VALUES ('EMPRESA', 'CODENDERECO', 'Cód. Endereço');

-- DICIONARIO ENDERECO
INSERT INTO DICIONARIO VALUES ('ENDERECO','CODENDERECO', 'Cód. Endereço');
INSERT INTO DICIONARIO VALUES ('ENDERECO','RUA', 'Rua');
INSERT INTO DICIONARIO VALUES ('ENDERECO','NUMERO', 'Número');
INSERT INTO DICIONARIO VALUES ('ENDERECO','COMPLEMENTO', 'Complemento');
INSERT INTO DICIONARIO VALUES ('ENDERECO','BAIRRO', 'Bairro');
INSERT INTO DICIONARIO VALUES ('ENDERECO','CEP', 'CEP');
INSERT INTO DICIONARIO VALUES ('ENDERECO','CIDADE', 'Cidade');
INSERT INTO DICIONARIO VALUES ('ENDERECO','ESTADO', 'Estado');
INSERT INTO DICIONARIO VALUES ('ENDERECO','PAIS', 'País');
INSERT INTO DICIONARIO VALUES ('ENDERECO', 'NOME', 'Nome');

-- DICIONARIO PRODUTO
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'CODEMPRESA', 'Cód. Empresa');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'CODPRODUTO', 'Cód. Produto');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'TIPO', 'Tipo Produto');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'ATIVO', 'Ativo');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'NOME', 'Nome do Produto');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'DESCRICAO', 'Descrição');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'PRECOUNITARIO', 'Preço Unitário');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'CODCLASSIFICACAO', 'Classificação');
INSERT INTO DICIONARIO VALUES ('PRODUTO', 'NOME1', 'Nome Classificação');

-- DICIONARIO CLIENTE/FORNECEDOR
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'CODEMPRESA', 'Cód. Empresa');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'CODCLIFOR', 'Cliente/Fornecedor');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'NOME', 'Nome');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'NOMEFANTASIA', 'Nome Fantasia');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'CNPJCPF', 'CNPJ/CPF');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'TELEFONE', 'Telefone');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'TIPOCADASTRO', 'Tipo Cadastro');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'TIPOPESSOA', 'Tipo Pessoa');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'EMAIL', 'Email');
INSERT INTO DICIONARIO VALUES ('CLIENTEFORNECEDOR', 'CODENDERECO', 'Cód. Endereço');

-- DICIONARIO CLASSIFICACAO
INSERT INTO DICIONARIO VALUES ('CLASSIFICACAO', 'CODEMPRESA', 'Cód. Empresa');
INSERT INTO DICIONARIO VALUES ('CLASSIFICACAO', 'CODCLASSIFICACAO', 'Classificação');
INSERT INTO DICIONARIO VALUES ('CLASSIFICACAO', 'NOME', 'Nome');
INSERT INTO DICIONARIO VALUES ('CLASSIFICACAO', 'DESCRICAO', 'Descrição'); 

-- DICIONARIO MOVIMENTAÇÃO
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'CODEMPRESA', 'Cód. Empresa');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'CODMOVIMENTACAO ', 'Cód. Movimentação');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'STATUS', 'Status');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'VALORTOTAL', 'Valor Total');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'CODUSUARIO', 'Usuário');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'CODCLIFOR', 'Cliente/Fornecedor');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'TIPOMOVIMENTO', 'Tipo');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'DATA', 'Data Criação');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAO', 'OBSERVACAO', 'Observação');

-- DICIONARIO MOVIMENTAÇÃO ITEM
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'CODEMPRESA', 'Cód. Empresa');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'CODMOVIMENTACAO ', 'Cód. Movimentação');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'CODMOVIMENTACAOITEM', 'Cód. Item Movimentação');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'CODPRODUTO', 'Cód. Produto');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'QUANTIDADE', 'Quantidade');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'VALORUNITARIO', 'Valor Unitário');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'CUSTOUNITARIO', 'Custo Unitário');
INSERT INTO DICIONARIO VALUES ('MOVIMENTACAOITEM ', 'VALORTOTAL', 'Valor Total');

INSERT INTO USUARIO VALUES ('1', 'Administrador do Sistema', 'master', '$2b$12$Y6wnGkZXQzTd7Ifo0Tq3NOIiqX5d363erDfp/g1MubFqzl9mpCUMG', 1, now());
INSERT INTO ENDERECO (CODENDERECO, NOME, RUA, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, PAIS)
VALUES (
    1, 
    'Empresa IBM', 
    'Avenida Paulista', 
    '813', 
    NULL,
    'Jardim Nossa Senhora de Fátima', 
    '13478-580', 
    'Americana', 
    'SP', 
    'Brasil'
);
INSERT INTO EMPRESA (CODEMPRESA, NOMEFANTASIA, NOME, CNPJ, TELEFONE, EMAIL, IMAGEM, CODENDERECO)
VALUES (
    1, 
    'IBM', 
    'International Business Machines Corporation', 
    '33.372.251/0001-56', 
    NULL,
    NULL, 
    NULL, 
    1     
);